from . import client_type
from . import client_client
from . import client_project
from . import employee_degree
from . import hr_employee
from . import export_employee_detail
from . import account
from . import hr_contract
from . import employee_family
from . import res_partner_account_inherit
