{
    'name': 'flint Helpdesk',
    'version': '17.1',
    'summary': 'help desk customisation for SDE',
    'description': 'help desk customisation for SDE',
    'category': 'Services/Helpdesk',
    'author': 'Omar Abdeif',
    'license': 'AGPL-3',
    'depends': ['scs_hr_employee',
                'helpdesk',
                'hr_employee_code',
                'scs_operation',
                ],
    'data': ['views/helpdesk_views.xml',
             'views/helpdesk_type_views.xml',
             'views/helpdesk_stage_views.xml',
             'views/service_type_views.xml',
             'views/government_payment_views.xml',
             'views/hr_employee_views.xml',
             'security/group_data.xml',
             'security/ir.model.access.csv',
             'views/logistic_order_views.xml',
             'data/mail_template_data.xml',
             'data/sequence.xml',
             # 'data/insurance_class_data.xml',  # Managed by migration script to avoid duplicate key errors
             'wizard/post_attachment_wizard_views.xml',
             'wizard/operation_on_hold_ticket_reason.xml',
             'views/account_payment_views.xml'],
    'installable': True,
    'auto_install': False,
}
