{
    'name': 'Employee Operation',
    'version': '17.0.1.0.1',  # Fix for insurance class migration
    'summary': '',
    'description': '',
    'category': 'HR',
    'author': 'Serpent Consulting Services Pvt. Ltd. & Omar Abdeif',
    'website': '',
    'license': 'AGPL-3',
    'depends': [
        'base',
        'mail',
        'account',
        'scs_hr_employee',
        'helpdesk',
        'account_accountant'
    ],
    'data': [
        'views/hotel_location_views.xml',
        'views/logistic_order_views.xml',
        'views/airport_airport_views.xml',
        'data/res_groups_data.xml',
        'data/insurance_policy_data.xml',
        'views/flight_bidding_views.xml',
        'views/portal_templates.xml',
        'views/res_config_settings_views.xml',
        'views/account_payment_views.xml',
        'views/government_payment_view.xml',
        'views/service_type_view.xml',
        'views/res_partner_views.xml',
        'views/employee_views.xml',
        'views/employee_data_views.xml',
        'views/insurance_class_views.xml',
        'views/insurance_policy_views.xml',
        'views/insurance_bulk_wizard_views.xml',
        'views/internal_sale_view.xml',
        'views/sister_company_views.xml',
        'views/document_type.xml',
        'views/account_move.xml',
        'views/menuitems.xml',
        'security/ir.model.access.csv',
        'data/server_actions.xml',
        'data/activity.xml',
        # 'data/insurance_class_data.xml',
        'data/mail_template.xml',
        'data/mail_template_data.xml',
        'data/sequence.xml',
        'data/product_data.xml',
        'data/fix_attachments_action.xml',
        'data/cron_fix_attachments.xml',
        'data/fix_insurance_class_action.xml',
        'wizards/rejection_reason_wizard_views.xml',
        'wizards/validate_payment_on_company_wizard_views.xml',
        'wizards/logistic_order_send_selection_views.xml',
        'wizards/fix_attachments_wizard_views.xml',
        'reports/flight_logistics_report.xml',
        'reports/flight_ticket_report.xml',
        'views/attachment_view.xml'

    ],
    'assets': {
        'web.assets_frontend': [
            'scs_operation/static/src/js/flight_bidding.js',
            'scs_operation/static/src/xml/flight_bidding.xml',
            'scs_operation/static/src/css/style.css',
            'scs_operation/static/src/css/flight_bidding_portal.css',
        ]
    },
    'installable': True,
    'auto_install': False,
    'application': False,
    'migrations': {
        '17.0.1.0.0': [
            'pre/rename_insurance_class_field',
            'post/migrate_insurance_policy_to_class',
        ],
    },
    'tests': [
        'tests/test_insurance_class_migration.py',
    ],
}
