from . import res_config_settings
from . import res_company
from . import res_bank
from . import saib_api
from . import saib_api_auth
from . import saib_bank_statement_line
from . import saib_bank_statement
from . import saib_payment
from . import saib_payroll_line
from . import saib_payroll
from . import hr_payslip_run
from . import res_partner_bank
from . import res_partner
