import json
from base64 import b64decode, b64encode
from lxml import etree
from odoo import fields, models, api
from odoo.tools import float_repr
import base64
import logging

_logger = logging.getLogger(__name__)


class AccountMove(models.Model):
    _inherit = "account.move"

    attachment_id = fields.Many2one(
        comodel_name='ir.attachment',
        help="The file generated by edi_format_id when the invoice is posted (and this document is processed).",
    )

    @api.depends('amount_total_signed', 'amount_tax_signed', 'l10n_sa_confirmation_datetime',
                 'company_id', 'company_id.vat', 'journal_id',
                 'journal_id.l10n_sa_production_csid_json',
                 'l10n_sa_invoice_signature', 'l10n_sa_chain_index')
    def _compute_qr_code_str(self):
        """Compute QR code string for Saudi Arabian invoices.
        Handles both ZATCA Phase 2 and traditional QR codes."""

        def get_qr_encoding(tag, field):
            """Helper function to encode QR code fields"""
            field_bytes = field.encode()
            return (
                    tag.to_bytes(length=1, byteorder='big') +
                    len(field_bytes).to_bytes(length=1, byteorder='big') +
                    field_bytes
            )

        def compute_traditional_qr(record):
            """Compute traditional (pre-ZATCA) QR code"""
            if not (record.l10n_sa_confirmation_datetime and record.company_id.vat):
                return ''

            time_sa = fields.Datetime.context_timestamp(
                record.with_context(tz='Asia/Riyadh'),
                record.l10n_sa_confirmation_datetime
            )

            qr_content = b''.join([
                get_qr_encoding(1, record.company_id.display_name),
                get_qr_encoding(2, record.company_id.vat),
                get_qr_encoding(3, time_sa.isoformat()),
                get_qr_encoding(4, float_repr(abs(record.amount_total_signed), 2)),
                get_qr_encoding(5, float_repr(abs(record.amount_tax_signed), 2))
            ])

            return base64.b64encode(qr_content).decode()

        def compute_zatca_qr(move):
            """Compute ZATCA Phase 2 QR code"""
            try:
                edi_format = self.env.ref('l10n_sa_edi.edi_sa_zatca')
                zatca_document = move.edi_document_ids.filtered(
                    lambda d: d.edi_format_id == edi_format
                )

                if move._l10n_sa_is_simplified():
                    # Handle simplified tax invoice
                    csid_json = json.loads(move.journal_id.l10n_sa_production_csid_json)
                    x509_cert = csid_json['binarySecurityToken']
                    xml_content = edi_format._l10n_sa_generate_zatca_template(move)

                    qr_code_str = move._l10n_sa_get_qr_code(
                        move.journal_id,
                        xml_content,
                        b64decode(x509_cert),
                        move.l10n_sa_invoice_signature,
                        move._l10n_sa_is_simplified()
                    )
                    return b64encode(qr_code_str).decode()

                elif zatca_document.state == 'sent' and zatca_document.sudo().attachment_id.datas:
                    # Handle standard tax invoice
                    document_xml = zatca_document.sudo().attachment_id.with_context(
                        bin_size=False
                    ).datas.decode()

                    root = etree.fromstring(b64decode(document_xml))
                    qr_node = root.xpath('//*[local-name()="ID"][text()="QR"]/following-sibling::*/*')[0]
                    return qr_node.text

            except Exception as e:
                # Log error for debugging but don't break the UI
                _logger.error("Error computing ZATCA QR code: %s", str(e))
                return ''

            return ''

        for move in self:
            move.l10n_sa_qr_code_str = ''

            if move.country_code != 'SA' or move.move_type not in ('out_invoice', 'out_refund'):
                continue

            if move.l10n_sa_chain_index:
                move.l10n_sa_qr_code_str = compute_zatca_qr(move)
            else:
                move.l10n_sa_qr_code_str = compute_traditional_qr(move)

    def action_post(self):
        """Reset chain index before posting"""
        for inv in self:
            if inv.l10n_sa_chain_index:
                inv.l10n_sa_chain_index = 0
        return super(AccountMove, self).action_post()