# -*- coding: utf-8 -*-
{
    'name': 'HR Letters & Contracts',
    'version': '1.0',
    'summary': 'HR Letters & Contracts',
    'description': """
        This module allows HR to manage and generate official letters and notices,
        including Job Offer Letters, Salary Increment Letters, Contract Extensions,
        Termination Notices, and Decline/Non-Renewal Notices And Many More.
    """,
    'category': 'HR',
    'author': 'Muhammad Hamza Faizan | Flint International',
    'depends': ['scs_hr_employee','scs_operation'],
    'data': [
        'security/ir.model.access.csv',
        'reports/contract_extension_action.xml',
        'reports/contract_extension_template.xml',
        'reports/contractor_access_action.xml',
        'reports/contractor_access_template.xml',
        # 'reports/contract_decline_action.xml',
        # 'reports/contract_decline_template.xml',
        'reports/experience_certificate_action.xml',
        'reports/experience_certificate_template.xml',
        'reports/job_offer_action.xml',
        'reports/job_offer_template.xml',
        'reports/salary_increment_action.xml',
        'reports/salary_increment_template.xml',
        'reports/agreement_termination_report_template.xml',
        'reports/agreement_termination_report_action.xml',
        # 'reports/job_offer_letter_report_action.xml',
        # 'reports/job_offer_letter_template.xml',
        'reports/loan_applictaion_report_action.xml',
        'reports/loan_application_report_template.xml',
        'reports/clearance_certificate_action.xml',
        'reports/clearance_certificate_template.xml',
        'reports/saudi_culture_office_template.xml',
        'reports/saudi_culture_office_action.xml',
        'reports/no_desire_to_renew_contract_template.xml',
        'reports/no_desire_to_renew_contract_action.xml',
        'views/job_offer_info.xml',
        'views/contractor_access_info.xml',
        'views/experience_certificate_info.xml',
        'views/salary_increment_info.xml',
        'views/contract_extension_info.xml',
        # 'views/contract_decline_info.xml',
        'views/agreement_termination.xml',
        # 'views/job_offer_letter.xml',
        'views/loan_application.xml',
        'views/clearance_certificate.xml',
        'views/saudi_culture_office.xml',
        'views/no_desire_to_renew_contract.xml',
        'views/menuitem.xml',
    ],
    'installable': True,
    'application': True,
}
